package com.p1_7.game.logic;

import com.badlogic.gdx.Gdx;
import com.p1_7.game.dungeon.DungeonConfig;
import com.p1_7.game.dungeon.DungeonGenerator;
import com.p1_7.game.dungeon.DungeonMap;
import com.p1_7.game.question.Question;
import com.p1_7.game.question.QuestionGenerator;

import java.util.List;
import java.util.Random;

/**
 * glue layer that drives one dungeon floor by sequencing DungeonGenerator,
 * QuestionGenerator, and RoomLabeller.
 *
 * call startLevel(int) to populate the three per-level fields; getMap,
 * getLabelledRooms, and getQuestion are only valid after that call succeeds.
 * a single GameState instance is owned here so callers do not need to manage
 * it separately.
 */
public class LevelOrchestrator {

    /** number of rooms to assign answer labels on each floor; fixed for all levels */
    private static final int ANSWER_ROOM_COUNT = 3;

    /** tag used for gdx logging */
    private static final String LOG_TAG = "LevelOrchestrator";

    // -- services (stateless, instantiated once) --

    private final DungeonGenerator  dungeonGenerator;
    private final QuestionGenerator questionGenerator;
    private final RoomLabeller      roomLabeller;

    // -- shared state --

    private final GameState gameState;

    // single rng shared across question and room labelling;
    // call order within startLevel determines the random sequence — do not reorder
    private final Random rng;

    // -- per-level results (non-null after startLevel succeeds) --

    private DungeonMap         map;
    private List<LabelledRoom> labelledRooms;
    private Question           question;

    /**
     * constructs a LevelOrchestrator with all services initialised.
     *
     * call startLevel(int) before accessing getMap, getLabelledRooms, or getQuestion.
     */
    public LevelOrchestrator() {
        this.dungeonGenerator  = new DungeonGenerator();
        this.questionGenerator = new QuestionGenerator();
        this.roomLabeller      = new RoomLabeller();
        this.gameState         = new GameState();
        this.rng               = new Random();
    }

    /**
     * generates and labels one dungeon floor for the given level.
     *
     * the sequence is:
     * 1. generate a dungeon map from DungeonConfig.defaults()
     * 2. if the map has fewer than 2 rooms, log a warning and retry once with a new seed
     * 3. if the retry also produces fewer than 2 rooms, log an error and return early
     * 4. generate a question scaled to the level
     * 5. label the rooms using RoomLabeller
     *
     * after this method returns normally, all three per-level getters return non-null values.
     *
     * @param level the current dungeon level; passed to QuestionGenerator to control difficulty
     */
    public void startLevel(int level) {
        // attempt dungeon generation with a fresh config (uses nanoTime seed)
        DungeonConfig config = DungeonConfig.defaults();
        map = dungeonGenerator.generate(config);

        // if too few rooms were placed, warn and retry with a new seed
        if (map.getRooms().size() < 2) {
            Gdx.app.log(LOG_TAG, "dungeon had fewer than 2 rooms — retrying with new seed");
            DungeonConfig retryConfig = DungeonConfig.defaults();
            map = dungeonGenerator.generate(retryConfig);

            // if the retry also fails, labelling would throw — surface a clear message instead
            if (map.getRooms().size() < 2) {
                Gdx.app.error(LOG_TAG, "retry also produced fewer than 2 rooms; level cannot start");
                return;
            }
        }

        // generate the question for this level
        question = questionGenerator.generate(level, rng);

        // label rooms; DecoyGenerator is called internally by RoomLabeller
        labelledRooms = roomLabeller.label(map.getRooms(), question, ANSWER_ROOM_COUNT, rng);
    }

    /**
     * returns the dungeon map produced by the most recent startLevel call.
     *
     * @return the current DungeonMap
     * @throws IllegalStateException if startLevel has not been called successfully
     */
    public DungeonMap getMap() {
        if (map == null) {
            throw new IllegalStateException("startLevel must be called before getMap");
        }
        return map;
    }

    /**
     * returns the labelled rooms produced by the most recent startLevel call.
     *
     * @return the list of LabelledRoom objects
     * @throws IllegalStateException if startLevel has not been called successfully
     */
    public List<LabelledRoom> getLabelledRooms() {
        if (labelledRooms == null) {
            throw new IllegalStateException("startLevel must be called before getLabelledRooms");
        }
        return labelledRooms;
    }

    /**
     * returns the question generated by the most recent startLevel call.
     *
     * @return the current Question
     * @throws IllegalStateException if startLevel has not been called successfully
     */
    public Question getQuestion() {
        if (question == null) {
            throw new IllegalStateException("startLevel must be called before getQuestion");
        }
        return question;
    }

    /**
     * returns the shared GameState instance owned by this orchestrator.
     *
     * @return the GameState; always non-null
     */
    public GameState getGameState() {
        return gameState;
    }
}
